routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Quote
Route::group(['namespace' => 'Quote', 'as' => 'quote.', 'prefix' => '{slug}/quote'], function(){
    // Pages
    Route::group(['namespace' => 'Pages'], function() {
        // Start
        Route::group(['middleware' => ['findQuote:true']], function() {
            Route::get('start/{quoteUid?}', 'StartController@view')->name('start');
            Route::post('start/save/{quoteUid?}', 'StartController@save')->name('save');
        });

        Route::group(['middleware' => ['findQuote', 'checkStage']], function() {
            // Room
            Route::get('room/{quoteUid}', 'RoomController@view')->name('room');
            Route::post('room/{quoteUid}/save', 'RoomController@save')->name('room.save');

            // Menu
            Route::get('menu/{quoteUid}', 'MenuController@view')->name('menu');
            Route::post('menu/{quoteUid}/save', 'MenuController@save')->name('menu.save');

            // Menu Additions
            Route::get('additions/{quoteUid}', 'MenuAdditionsController@view')->name('additions');
            Route::post('additions/{quoteUid}/save', 'MenuAdditionsController@save')->name('additions.save');

            // Finish
            Route::get('finish/{quoteUid}', 'FinishController@view')->name('finish');
            Route::post('finish/{quoteUid}/cont', 'FinishController@cont')->name('finish.continue');
            Route::post('email/{quoteUid}', 'FinishController@email')->name('finish.email');
        });
    });

    // Review
    Route::get('review/{quoteUid}', 'QuoteController@review')
        ->name('review')
        ->middleware('findQuote');
});




Route::get('/home', 'HomeController@show');


Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function() {
    Route::group(['as' => 'rooms.', 'prefix' => 'rooms'], function() {
        Route::get('', 'RoomController@index')->name('index');
        Route::get('add', 'RoomController@add')->name('add');
        Route::post('', 'RoomController@store')->name('store');
        Route::get('edit/{id?}', 'RoomController@edit')->name('edit');
        Route::get('{id}', 'RoomController@show')->name('show');
        Route::put('{id}', 'RoomController@update')->name('update');
        Route::delete('{id}', 'RoomController@destroy')->name('destroy');
    });

    Route::group(['as' => 'menus.', 'prefix' => 'menus'], function() {
        Route::get('', 'MenuController@index')->name('index');
        Route::get('add', 'MenuController@add')->name('add');
        Route::post('', 'MenuController@store')->name('store');
        Route::get('edit/{id?}', 'MenuController@edit')->name('edit');
        Route::get('{id}', 'MenuController@show')->name('show');
        Route::put('{id}', 'MenuController@update')->name('update');
        Route::delete('{id}', 'MenuController@destroy')->name('destroy');
    });

    Route::group(['as' => 'menuAdditions.', 'prefix' => 'menuAdditions'], function() {
        Route::get('', 'MenuAdditionsController@index')->name('index');
        Route::get('add', 'MenuAdditionsController@add')->name('add');
        Route::post('', 'MenuAdditionsController@store')->name('store');
        Route::get('edit/{id?}', 'MenuAdditionsController@edit')->name('edit');
        Route::get('{id}', 'MenuAdditionsController@show')->name('show');
        Route::put('{id}', 'MenuAdditionsController@update')->name('update');
        Route::delete('{id}', 'MenuAdditionsController@destroy')->name('destroy');
    });

    Route::group(['as' => 'quotes.', 'prefix' => 'quotes'], function() {
        Route::get('', 'QuoteController@index')->name('index');
        Route::get('add', 'QuoteController@add')->name('add');
//        Route::post('', 'QuoteController@store')->name('store');
//        Route::get('edit/{id?}', 'QuoteController@edit')->name('edit');
        Route::get('{id}', 'QuoteController@show')->name('show');
//        Route::put('{id}', 'QuoteController@update')->name('update');
//        Route::delete('{id}', 'QuoteController@destroy')->name('destroy');
    });
});

app/Menu.php
<?php

namespace EventQuote;

use EventQuote\Traits\Activateable;
use EventQuote\Traits\BelongsToTeam;
use EventQuote\Traits\Orderable;
use EventQuote\Traits\TracksOwnerAndUpdater;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Menu extends Model
{
    use BelongsToTeam, Activateable, Orderable, TracksOwnerAndUpdater;

    /**
     * @inheritdoc
     */
    protected $fillable = [
        'name',
        'price_pp',
        'features',
        'abstract',
        'description',
        'min_persons',
        'max_persons',
        'order',
        'active'
    ];


    public function menuAdditions()
    {
        return $this->belongsToMany('EventQuote\MenuAddition');
    }


    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
        $this->ownerIDField = 'owner_id';
        $this->updaterIDField = 'user_id';
    }
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace EventQuote\Http\Controllers\Admin;

use EventQuote\Http\Requests\Admin\MenuRequest;
use EventQuote\Services\MenuService;
use Illuminate\Http\Request;
use EventQuote\Http\Controllers\Controller;

class MenuController extends Controller
{
    /**
     * @var MenuService
     */
    protected $menuService;


    public function __construct(MenuService $menuService)
    {
        $this->menuService = $menuService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $menus = $this->menuService->get();
        return view('admin.menus.index')
            ->with('menus', $menus);
    }

    public function add()
    {
        $view = view('admin.menus.edit');
        return $view;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  MenuRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(MenuRequest $request)
    {
        $data = $request->all();
        $newMenu = $this->menuService->create($data);
        return redirect()
            ->route('admin.menus.show', $newMenu->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $menu = $this->menuService->find($id);
        return view('admin.menus.show')
            ->with('menu', $menu);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id = null)
    {
        $view = view('admin.menus.edit');
        if ($id) {
            $menu = $this->menuService->find($id);
            $view->with('menu', $menu);
        }
        return $view;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(MenuRequest $request, $id)
    {
        $this->menuService->update($id, $request->all());
        return redirect()->route('admin.menus.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->menuService->delete($id);
        return redirect()->route('admin.menus.index');
    }
}

app/Http/Controllers/Quote/Pages/MenuController.php
<?php

namespace EventQuote\Http\Controllers\Quote\Pages;

use EventQuote\Http\Requests\Quote\MenuRequest;
use EventQuote\Facades\Menu;
use EventQuote\Services\MailService;
use Illuminate\Http\Request;
use EventQuote\Http\Controllers\Quote\QuotePageController;

class MenuController extends QuotePageController
{
    public static $template = 'quote.pages.menu';
    public static $viewRoute = 'quote.menu';
    public static $saveRoute = 'quote.menu.save';
    public static $displayName = 'Menu';
    public static $summary = '_partials.quote.summary';
    public static $id = 4;


    public function view(Request $request)
    {
        $menus = Menu::getPublic();
        return parent::view($request)
            ->with('menus', $menus);
    }


    public function save(MenuRequest $request)
    {
        $quote = $request->input('quote');
        $team = $request->input('team');
        $quote->menu_id = $request->input('menu_id');

        if(!count($team->menuAdditions)){
            MailService::mailFinishedQuote($quote);
        }

        return parent::saveAndContinue($request, $quote, $team);
    }
}

resources/views/admin/menus/edit.blade.php
@extends('spark::layouts.app')

@section('content')
<div class="container" style="width: 100%">
<div class="panel panel-default">
    <h3 class="panel-heading">{{ isset($menu) ? "Edit Menu" : "Add New Menu" }}</h3>

    <div class="panel-body" style="padding: 0 1500px 1100px 100px">
        @if(isset($menu))
            {!! Form::model($menu, ['route' => ['admin.menus.update', $menu->id], 'method' => 'PUT']) !!}
        @else
            {!! Form::open(['route' => 'admin.menus.store']) !!}
        @endif
            <div class="form-group">
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null,  ['class' => 'form-control']) !!}
                <span class="is-danger">{{ $errors->first('name') }}</span>
            </div>

            <div class="form-group">
                {!! Form::label('price_pp', 'Price (per person)') !!}
                {!! Form::number('price_pp', null, ['min'=>0]) !!}
                <span class="is-danger">{{ $errors->first('price_pp') }}</span>
            </div>

            @foreach(['features', 'abstract', 'description'] as $key)
                <div class="form-group">
                    {!! Form::label($key, title_case($key)) !!}
                    {!! Form::textarea($key, null,  ['class' => 'form-control']) !!}
                    <span class="is-danger">{{ $errors->first($key) }}</span>
                </div>
            @endforeach

            @foreach(['min_persons', 'max_persons'] as $key)
                <div class="form-group">
                    {!! Form::label($key, title_case($key)) !!}
                    {!! Form::number($key, null, ['min'=>1]) !!}
                    <span class="is-danger">{{ $errors->first($key) }}</span>
                </div>
            @endforeach

            <div class="form-group">
                {!! Form::hidden('active', 0) !!}
                {!! Form::checkbox('active', 1, isset($menu) ? $menu->active : true) !!}
                {!! Form::label('active', 'Active') !!}
                <span class="is-danger">{{ $errors->first('active') }}</span>
            </div>

            <div class="form-group">
                {!! Form::label('order', 'Order') !!}
                {!! Form::number('order', null, ['class' => 'form-control']) !!}
                <p class="help-block">Choose a number to select which position this new room will be displayed in or leave as zero to place it last.</p>
                <span class="is-danger">{{ $errors->first('order') }}</span>
            </div>

            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}

            @if(isset($menu))
                <a href="{{ route('admin.menus.show', $menu->id) }}" class="btn">
                    Cancel
                </a>
            @else
                <a href="{{ route('admin.menus.index') }}" class="btn">
                    Cancel
                </a>
            @endif
        {!! Form::close() !!}
    </div>
</div>
</div>
@endsection

resources/views/admin/menus/index.blade.php
@extends('spark::layouts.app')

@section('content')
    <div class="container" style="width: 100%">
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{{ route('admin.menus.add') }}" class="btn btn-primary">Add New Menu</a>
            </div>
            <div class="panel-body">
                <table border="1">
                    <tr>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Features</th>
                        <th>Description</th>
                        <th>Abstract</th>
                        <th>Size</th>
                        <th></th>
                    </tr>
                    @foreach($menus as $menu)
                        <tr>
                            <td>
                                <p>{{ $menu->name ? $menu->name : 'N/A' }}</p>
                            </td>

                            <td>
                                <p>${{ $menu->price_pp ? $menu->price_pp : 'N/A' }}</p>
                            </td>

                            <td>
                                <p>{{ $menu->features ? $menu->features : 'N/A' }}</p>
                            </td>

                            <td>
                                <p>
                                    {!! nl2br(e($menu->description ? $menu->description : 'N/A')) !!}
                                </p>
                            </td>

                            <td>
                                <p>{{ $menu->abstract ? $menu->abstract : 'N/A' }}</p>
                            </td>

                            <td>
                                <p>{{ $menu->min_persons ? $menu->min_persons : 'N/A' }}-{{ $menu->max_persons ? $menu->max_persons : 'N/A' }}</p>
                            </td>

                            <td style="width: 180px">
                                <a href="{{ route('admin.menus.edit', $menu->id) }}" class="btn btn-primary">Edit</a>

                                {!! Form::open(['method' => 'delete', 'route' => ['admin.menus.destroy', $menu->id], 'style'=>'float:right; height:0']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/menus/show.blade.php
@extends('spark::layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="panel panel-default">
                <h3 class="panel-heading">
                    {{ $menu->name }}
                </h3>

                <div class="panel-body">
                    @foreach(['price_pp', 'features', 'abstract', 'description'] as $key)
                        <strong>{{ title_case($key) }}</strong>
                        <p>{{ $menu[$key] }}</p>
                    @endforeach

                    {{--<a href="{{ route('admin.menus.edit', $menu->id) }}" class="btn btn-primary">Edit</a>--}}

                    {{--{!! Form::open(['method' => 'delete', 'route' => ['admin.menus.destroy', $menu->id], 'style'=>'float:right']) !!}--}}
                        {{--{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}--}}
                    {{--{!! Form::close() !!}--}}
                </div>
            </div>
        </div>
    </div>
@endsection